target-version = "py310"


[lint]
extend-select = [
    "UP",  # pyupgrade
    "D",   # pydocstyle,
    "PERF",
    "NPY",
    "PL",
    "PD",
    "RET",
    "INT",
    "PTH",
    "ERA",
    "RSE",
    "ISC",
    "B"
]
ignore = ["D212", "D211", "D203", "ISC001"]